/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface EventsInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "AgentCancelled"
      | "AgentCreated"
      | "AgentPaused"
      | "AgentResumed"
      | "AgentUpdated"
      | "FeeCollectorUpdated"
      | "PaymentExecuted"
      | "PlatformFeeUpdated"
  ): EventFragment;
}

export namespace AgentCancelledEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentCreatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    name: string,
    agentType: BigNumberish,
    frequency: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    name: string,
    agentType: bigint,
    frequency: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    name: string;
    agentType: bigint;
    frequency: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentPausedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentResumedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    name: string,
    amount: BigNumberish,
    frequency: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    name: string,
    amount: bigint,
    frequency: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    name: string;
    amount: bigint;
    frequency: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [newCollector: AddressLike];
  export type OutputTuple = [newCollector: string];
  export interface OutputObject {
    newCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    recipient: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    recipient: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Events extends BaseContract {
  connect(runner?: ContractRunner | null): Events;
  waitForDeployment(): Promise<this>;

  interface: EventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "AgentCancelled"
  ): TypedContractEvent<
    AgentCancelledEvent.InputTuple,
    AgentCancelledEvent.OutputTuple,
    AgentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AgentCreated"
  ): TypedContractEvent<
    AgentCreatedEvent.InputTuple,
    AgentCreatedEvent.OutputTuple,
    AgentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentPaused"
  ): TypedContractEvent<
    AgentPausedEvent.InputTuple,
    AgentPausedEvent.OutputTuple,
    AgentPausedEvent.OutputObject
  >;
  getEvent(
    key: "AgentResumed"
  ): TypedContractEvent<
    AgentResumedEvent.InputTuple,
    AgentResumedEvent.OutputTuple,
    AgentResumedEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentCancelled(uint256)": TypedContractEvent<
      AgentCancelledEvent.InputTuple,
      AgentCancelledEvent.OutputTuple,
      AgentCancelledEvent.OutputObject
    >;
    AgentCancelled: TypedContractEvent<
      AgentCancelledEvent.InputTuple,
      AgentCancelledEvent.OutputTuple,
      AgentCancelledEvent.OutputObject
    >;

    "AgentCreated(uint256,address,string,uint8,uint8,uint256)": TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;
    AgentCreated: TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;

    "AgentPaused(uint256)": TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;
    AgentPaused: TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;

    "AgentResumed(uint256)": TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;
    AgentResumed: TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;

    "AgentUpdated(uint256,string,uint256,uint8)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "FeeCollectorUpdated(address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "PaymentExecuted(uint256,address,uint256,uint256)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
  };
}
