/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DataTypes {
  export type PaymentStruct = {
    agentId: BigNumberish;
    recipient: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    txHash: BytesLike;
  };

  export type PaymentStructOutput = [
    agentId: bigint,
    recipient: string,
    amount: bigint,
    timestamp: bigint,
    txHash: string
  ] & {
    agentId: bigint;
    recipient: string;
    amount: bigint;
    timestamp: bigint;
    txHash: string;
  };
}

export interface RecurChainAgentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentCounter"
      | "agentPayments"
      | "agents"
      | "cancelAgent"
      | "createAgent"
      | "executePayment"
      | "feeCollector"
      | "getAgent"
      | "getAgentPayments"
      | "getAgentSummary"
      | "getUserAgents"
      | "isAgentReadyForExecution"
      | "owner"
      | "pause"
      | "pauseAgent"
      | "paused"
      | "platformFee"
      | "renounceOwnership"
      | "resumeAgent"
      | "transferOwnership"
      | "unpause"
      | "updateAgent"
      | "updateFeeCollector"
      | "updatePlatformFee"
      | "usdcToken"
      | "userAgents"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentCancelled"
      | "AgentCreated"
      | "AgentPaused"
      | "AgentResumed"
      | "AgentUpdated"
      | "FeeCollectorUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentExecuted"
      | "PlatformFeeUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentPayments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgent",
    values: [
      string,
      BigNumberish,
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentPayments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentReadyForExecution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resumeAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userAgents",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgentReadyForExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pauseAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userAgents", data: BytesLike): Result;
}

export namespace AgentCancelledEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentCreatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    name: string,
    agentType: BigNumberish,
    frequency: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    name: string,
    agentType: bigint,
    frequency: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    name: string;
    agentType: bigint;
    frequency: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentPausedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentResumedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    name: string,
    amount: BigNumberish,
    frequency: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    name: string,
    amount: bigint,
    frequency: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    name: string;
    amount: bigint;
    frequency: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [newCollector: AddressLike];
  export type OutputTuple = [newCollector: string];
  export interface OutputObject {
    newCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    recipient: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    recipient: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RecurChainAgent extends BaseContract {
  connect(runner?: ContractRunner | null): RecurChainAgent;
  waitForDeployment(): Promise<this>;

  interface: RecurChainAgentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentCounter: TypedContractMethod<[], [bigint], "view">;

  agentPayments: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        agentId: bigint;
        recipient: string;
        amount: bigint;
        timestamp: bigint;
        txHash: string;
      }
    ],
    "view"
  >;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        owner: string;
        name: string;
        agentType: bigint;
        description: string;
        recipient: string;
        amount: bigint;
        frequency: bigint;
        startDate: bigint;
        nextExecutionTime: bigint;
        isActive: boolean;
        executionCount: bigint;
        totalPaid: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  cancelAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createAgent: TypedContractMethod<
    [
      _name: string,
      _agentType: BigNumberish,
      _description: string,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _frequency: BigNumberish,
      _startDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  executePayment: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  getAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        owner: string;
        name: string;
        agentType: bigint;
        description: string;
        recipient: string;
        amount: bigint;
        frequency: bigint;
        startDate: bigint;
        nextExecutionTime: bigint;
        isActive: boolean;
        executionCount: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;

  getAgentPayments: TypedContractMethod<
    [agentId: BigNumberish],
    [DataTypes.PaymentStructOutput[]],
    "view"
  >;

  getAgentSummary: TypedContractMethod<
    [agentId: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        name: string;
        amount: bigint;
        frequencyStr: string;
        recipient: string;
        nextRun: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getUserAgents: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  isAgentReadyForExecution: TypedContractMethod<
    [agentId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauseAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resumeAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateAgent: TypedContractMethod<
    [
      agentId: BigNumberish,
      _name: string,
      _description: string,
      _amount: BigNumberish,
      _frequency: BigNumberish,
      _recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  updateFeeCollector: TypedContractMethod<
    [_newCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlatformFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  userAgents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentPayments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        agentId: bigint;
        recipient: string;
        amount: bigint;
        timestamp: bigint;
        txHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        owner: string;
        name: string;
        agentType: bigint;
        description: string;
        recipient: string;
        amount: bigint;
        frequency: bigint;
        startDate: bigint;
        nextExecutionTime: bigint;
        isActive: boolean;
        executionCount: bigint;
        totalPaid: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAgent"
  ): TypedContractMethod<
    [
      _name: string,
      _agentType: BigNumberish,
      _description: string,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _frequency: BigNumberish,
      _startDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        owner: string;
        name: string;
        agentType: bigint;
        description: string;
        recipient: string;
        amount: bigint;
        frequency: bigint;
        startDate: bigint;
        nextExecutionTime: bigint;
        isActive: boolean;
        executionCount: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentPayments"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [DataTypes.PaymentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentSummary"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        name: string;
        amount: bigint;
        frequencyStr: string;
        recipient: string;
        nextRun: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserAgents"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isAgentReadyForExecution"
  ): TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resumeAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      _name: string,
      _description: string,
      _amount: BigNumberish,
      _frequency: BigNumberish,
      _recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFeeCollector"
  ): TypedContractMethod<[_newCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userAgents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AgentCancelled"
  ): TypedContractEvent<
    AgentCancelledEvent.InputTuple,
    AgentCancelledEvent.OutputTuple,
    AgentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AgentCreated"
  ): TypedContractEvent<
    AgentCreatedEvent.InputTuple,
    AgentCreatedEvent.OutputTuple,
    AgentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentPaused"
  ): TypedContractEvent<
    AgentPausedEvent.InputTuple,
    AgentPausedEvent.OutputTuple,
    AgentPausedEvent.OutputObject
  >;
  getEvent(
    key: "AgentResumed"
  ): TypedContractEvent<
    AgentResumedEvent.InputTuple,
    AgentResumedEvent.OutputTuple,
    AgentResumedEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AgentCancelled(uint256)": TypedContractEvent<
      AgentCancelledEvent.InputTuple,
      AgentCancelledEvent.OutputTuple,
      AgentCancelledEvent.OutputObject
    >;
    AgentCancelled: TypedContractEvent<
      AgentCancelledEvent.InputTuple,
      AgentCancelledEvent.OutputTuple,
      AgentCancelledEvent.OutputObject
    >;

    "AgentCreated(uint256,address,string,uint8,uint8,uint256)": TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;
    AgentCreated: TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;

    "AgentPaused(uint256)": TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;
    AgentPaused: TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;

    "AgentResumed(uint256)": TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;
    AgentResumed: TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;

    "AgentUpdated(uint256,string,uint256,uint8)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "FeeCollectorUpdated(address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentExecuted(uint256,address,uint256,uint256)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
